name: Nautilus Workflow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build Nautilus
      run: cargo build --verbose
    - name: Test Nautilus
      run: cargo test --verbose
